### ISSUE TITLE
Define prev and next links

### ISSUE THREAD

**Issue by alrick** [getgrav/grav-theme-learn2#14]
Hey there!

I just installed the learn2 theme but I can't figure how to define the prev and next links, is there an easy way to do it?

Thanks

**Comment by flaviocopes** [comment]
They are added automatically to all 'docs.md' pages with `taxonomy.category: docs`, see https://github.com/getgrav/grav-theme-learn2/blob/develop/templates/docs.html.twig#L6

and how it works on the Learn Site: https://raw.githubusercontent.com/getgrav/grav-learn/develop/pages/08.cookbook/01.general-recipes/docs.md

**Comment by alrick** [comment]
Thank you!
