### ISSUE TITLE
Compatibility with grav-login

### ISSUE THREAD

**Issue by Kasparsu** [getgrav/grav-theme-learn2#17]
Is missing logout and logged in user showing area

**Comment by danielberkompas** [comment]
@Kasparsu it also seems to be missing the form fields necessary to even render the login form? Here's what I got when I tried to use `grav-login` with Learn2:

![whoops_there_was_an_error_](https://cloud.githubusercontent.com/assets/1186992/14061735/ebe4b136-f344-11e5-8928-a529c2145d04.png)

Was that your experience as well?

**Comment by flaviocopes** [comment]
@danielberkompas is that the latest stable Login plugin? Or checked out from GitHub?

**Comment by danielberkompas** [comment]
@flaviocopes I figured it out. For some reason, I didn't end up getting the `Form` dependency of `login`, so the form fields weren't present and available to render the login screen. Separate issue.
