### ISSUE TITLE
Question - How to use other Pure css styles such as buttons?

### ISSUE THREAD

**Issue by edwinyzh** [getgrav/grav-theme-learn2#21]
Hi,

There is a folder called `user\themes\learn2\css\pure-0.5.0`, so I assume the learn2 theme is based on the Pure CSS framework.

But it seems that it only includes the grid system. What are the steps for adding other purecss.io styles such as `buttons`, `menus` to the theme? 

Thanks.

**Comment by flaviocopes** [comment]
The easiest way is probably load the CSS using the Assets plugin: https://github.com/getgrav/grav-plugin-assets

The best way, which involves a bit more work, is to extend the theme (http://learn.getgrav.org/themes/customization#theme-inheritance) add any CSS library you want, and load it into the theme directly.

**Comment by edwinyzh** [comment]
Thanks for the instructions. One related question - once the additional css files are imported, I can write any raw html code in my page content (the .md file), right?

**Comment by flaviocopes** [comment]
Yes, you can write plain HTML in the markdown files. The best place to put HTML code however is in the Twig files.
