### ISSUE TITLE
How to use FontAwesome icons on a page

### ISSUE THREAD

**Issue by yoshikin** [getgrav/grav-theme-learn2#26]
I see that FontAwesome icons are used in this theme (for example in the sidebar). Is it possible to also use FontAwesome icons directly on a page? Is there a markdown shortcode for this?

**Comment by edwinyzh** [comment]
+1

**Comment by rhukster** [comment]
I've added FontAwesome to the **Shortcode-Core** plugin: https://github.com/getgrav/grav-plugin-shortcode-core#fontawesome

you an use it as simply as: `[fa=fa-cog /]`

**Comment by yoshikin** [comment]
Thanks for adding the shortcodes.

I prefer the emoji syle `:fa-cog:` so I made a quick plugin to handle these, too:

https://github.com/yoshikin/grav-plugin-markdown-fontawesome

It doesn't support additional `fa-` classes like `fa-spin` yet and the current implementation is not compatible with Markdown Extra (conflicts with definition lists), but it seems to work fine in most other cases.
