### ISSUE TITLE
Possible to have all menu items expanded by default?

### ISSUE THREAD

**Issue by KoreMike** [getgrav/grav-theme-learn2#28]
If you have a not very large manual, is it possible to have all menu items expanded by default?

Would this be an adjustment to the css or could it be done in blueprints.yaml?

**Comment by flaviocopes** [comment]
It's a CSS thing. You can add this CSS: `#sidebar h5+ul.topics, #sidebar ul.topics ul { display: block }`

**Comment by KoreMike** [comment]
Thanks Flaviio

**Comment by KoreMike** [comment]
Hello again Flavio!

I can't get this working.

If you look at the attached [themecss.txt](https://github.com/getgrav/grav-theme-learn2/files/253365/themecss.txt)  file, I have added: 

`#sidebar h5 + ul.topics, #sidebar ul.topics ul { display: block }`

At Line 158

I also removed the previous blocks:

`  #sidebar h5 + ul.topics {
    display: none;
    margin-top: 0; }
  #sidebar h5.parent + ul.topics, #sidebar h5.active + ul.topics {
    display: block; }`

As I thought they would be conflicting with the added line. I have also tried leaving them in, but nothing seems to work.
