### ISSUE TITLE
Search not working like the learn docs?

### ISSUE THREAD

**Issue by absolutejam** [getgrav/grav-theme-learn2#38]
Hey,

I just pulled the learn theme and it seems like the search box only searches on the current page. Is there something I need to do, or do the online docs use a different search mechanism?

Regards,
James.

**Comment by rhukster** [comment]
Use the "RTFM Skeleton" package.  This contains simplesearch plugin and has the content setup with the correct taxonomy so that search will work.  Available in the skeleton downloads.

**Comment by tamielbr** [comment]
I had problems setting the skeleton on my server. Any tips on how to configure this manually once simplesearch is installed?

**Comment by christianhals** [comment]
I just installed a new site with latest grav and learn2, but unfortunately the search is not working. It is just searching through the nav bar and highlighting hits. Nav tree are not filtered or expanded for hits.
