### ISSUE TITLE
allow to set root page for documentation

### ISSUE THREAD

**Issue by cord** [getgrav/grav-theme-learn2#4]
in combination with "themer" it is possible to apply learn2 only to a subset of pages.

By default all other top-level pages are shown.

By changing
user/themes/learn2/templates/partials/sidebar.html.twig, around line 46

from
` {{ _self.loop(pages, '') }}`

to
` {{ _self.loop(page.find('/documentation'), '') }}`

the documentation root starts with page /documentation.

Would be great to have a configuration setting for the root page

**Comment by rhukster** [comment]
I have merged your changes.  I think its a great addition!
