### ISSUE TITLE
Removing numbering

### ISSUE THREAD

**Issue by tylerhammer** [getgrav/grav-theme-learn2#41]
Is there anyway to remove numbering on the sidebar? I like the theme, but I'm using it for for a Wiki rather then an ordered documentation site.

**Comment by OptikWebCreative** [comment]
@tylerhammer sent you a SCSS snippet to resolve this in chat

**Comment by tylerhammer** [comment]
Thanks to some help from @OptikWebCreative and @OleVik on Gitter, I was able to resolve this issue. 

```
#sidebar ul.topics > li > a b
{
    visibility: hidden;
} 
```

Hidden was used as it didnt offset the text at all. 

Code was placed in /scsss/theme/_custom.scss 

Must be compiled afterwards.
