### ISSUE TITLE
"Template "default.html.twig" is not defined." on fresh install of theme

### ISSUE THREAD

**Issue by pianomanfrazier** [getgrav/grav-theme-learn2#57]
I am using php7 and installed the Learn2 theme and the error occurred.

**Comment by rhukster** [comment]
This is not a bug, learn2 is for documentation and only has support for 2 page type templates: 'chapter' and 'docs'.  there's no 'default' template. So you'll have to change any 'default' to one of those two.

**Comment by pianomanfrazier** [comment]
Thanks for the quick response.
