### ISSUE TITLE
missing <p> with lines starting with a site variable

### ISSUE THREAD

**Issue by the4thamigo-uk** [getgrav/grav-theme-learn2#64]
Removal of the `<p>` tags (in issue https://github.com/getgrav/grav-theme-learn2/issues/63) has affected the layout of some of our pages. It seems that those pages starting with a site variable dont wrap text with a `<p>`

e.g. this markdown :

```
---
title: a title
---
{{site.my_var}} text
```

incorrectly renders as:

```
<h1>a title</h1>
   my_val text
```

But this markdown :

```
---
title: a title
---
some {{site.my_var}} text
```

correctly renders as :

```
<h1>a title</h1>
  <p>my_var text</p>
```

**Comment by rhukster** [comment]
Try putting a newline above and below your content:

```
---
title: a title
---

{{site.my_var}} tex

```

**Comment by the4thamigo-uk** [comment]
I already tried that. Unfortunately it doesnt make any difference.

**Comment by rhukster** [comment]
Try putting this in your page header:

```
twig_frist: true
```

**Comment by the4thamigo-uk** [comment]
Yes that works, but can I apply that globally? Could this be considered a bug in grav?

**Comment by rhukster** [comment]
You can set this globally in the `user/config/system.yaml`, but it might have some affect on other pages.  You will need to test all your pages to make sure everything seems to render correctly.  I personally would only set it where I need it.

it's really not a bug, it's just a weird situation where the markdown parser does not recognize the `{{` twig syntax as the start of a paragraph, so its not wrapping it with `<p>` tags.  By setting `twig_first: true`, Grav is processing Twig 'first' so when markdown gets to it, it's just text, and it processes as expected.  Your going to have to set this option as you need it.
