### ISSUE TITLE
Internet Explorer Support

### ISSUE THREAD

**Issue by rmrten** [getgrav/grav-theme-learn2#77]
Hi,

Is there any documentation ( which i probably didnt find ) about IE support? I am experiencing several issues right now. I am not sure if it is Grav in general or Lear2 theme by itself only. Few Points:

- Rendering and side bar behavior ( IE issue in general i think ): every time you click on another page from side bar menu, side bar will be rerendered and visually appear again on refresh. 
- TNT Search and Basic serach : searching only if your input is only one letter. TNT Search not working at all

Probably i will find more ( hope not ). But on Firefox everything works fine right out of the box.

Thank you for any tips.

**Comment by rhukster** [comment]
It’s not grav  itself, its the theme.  We generally support Edge but don’t really put song effort into ie.

**Comment by rmrten** [comment]
Understand why :) Thanks anyway.
