### ISSUE TITLE
Problem adding Learn2 to Grav 1.7.5

### ISSUE THREAD

**Issue by rvreugde** [getgrav/grav-theme-learn2#90]
When I install the Learn2 theme in Grav 1.7.5, it is not visible in the admin section.
GUI and CMD line install tried (bin/gpm install learn2)
![image](https://user-images.githubusercontent.com/38208623/106920051-fbfe1a00-670a-11eb-9268-21b933002169.png)

But invisible:
![image](https://user-images.githubusercontent.com/38208623/106919669-a590db80-670a-11eb-8d33-a171de344fd4.png)

But present in the themes folder:
![image](https://user-images.githubusercontent.com/38208623/106920088-05878200-670b-11eb-85c4-05e4f4804bd6.png)

Can you help?

**Comment by rhukster** [comment]
Does clearing cache help?

**Comment by rvreugde** [comment]
Clearing All cache...
Purge Old Cache...

Does not solve the problem...

**Comment by rhukster** [comment]
I just tested with the "RTFM" skeleton package (updated to Grav 1.7 then installed Admin from CLI), and it shows fine.

I suggest if you want to build a 'learn2' based theme, you use RTFM skeleton as the based as it uses different page templates (chapter and docs) compared to the standard Grav.

<img width="852" alt="CleanShot 2021-02-05 at 13 47 15@2x" src="https://user-images.githubusercontent.com/1084697/107087589-e3e4d400-67b8-11eb-9d7a-803bd65817aa.png">

**Comment by holehan** [comment]
I had the same issue and fixed it by removing some superfluous tab characters from the theme's config file.

See pull request: https://github.com/getgrav/grav-theme-learn2/pull/91

**Comment by mahagr** [comment]
Merged the change.

**Comment by andrekutianski** [comment]
same problem here, impossible to activate the theme.

**Comment by rhukster** [comment]
1.8.2 released with fix and should be available soon.
